import React, { Component } from 'react';
import { Table, Tabs } from 'antd';
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faTachometerAlt, faAngleRight, faCheckSquare, faFileUpload, faPlayCircle, faCloud, faPencilRuler } from '@fortawesome/free-solid-svg-icons'
import './Dashboard.scss';

library.add(faTachometerAlt, faAngleRight, faCheckSquare, faFileUpload, faPlayCircle, faCloud, faPencilRuler)

const dataSource = [
  {
    key: '1',
    student: 'Dora  Townsend',
    a11self: '-',
    a12self: '-',
    a13self: '-',
    a14self: '-',
    check1: '-',
    quick1: '-',
    a21self: '-',
    a22self: '-',
    a23self: '-',
    a24self: '-',
    check2: '-',
    quick2: '-',
    a31self: '-',
    a32self: '-',
    a33self: '-',
    a34self: '-',
    check3: '-',
    quick3: '-',
    a41self: '-',
    a42self: '-',
    a43self: '-',
    a44self: '-',
    check4: '-',
    quick4: '-',
  },
  {
    key: '2',
    student: 'Manuel  Nichols',
    a11self: '-',
    a12self: '-',
    a13self: '-',
    a14self: '-',
    check1: '-',
    quick1: '-',
    a21self: '-',
    a22self: '-',
    a23self: '-',
    a24self: '-',
    check2: '-',
    quick2: '-',
    a31self: '-',
    a32self: '-',
    a33self: '-',
    a34self: '-',
    check3: '-',
    quick3: '-',
    a41self: '-',
    a42self: '-',
    a43self: '-',
    a44self: '-',
    check4: '-',
    quick4: '-',
  },
  {
    key: '3',
    student: 'Stella  Hawkins',
    a11self: '-',
    a12self: '-',
    a13self: '-',
    a14self: '-',
    check1: '-',
    quick1: '-',
    a21self: '-',
    a22self: '-',
    a23self: '-',
    a24self: '-',
    check2: '-',
    quick2: '-',
    a31self: '-',
    a32self: '-',
    a33self: '-',
    a34self: '-',
    check3: '-',
    quick3: '-',
    a41self: '-',
    a42self: '-',
    a43self: '-',
    a44self: '-',
    check4: '-',
    quick4: '-',
  },
  {
    key: '4',
    student: 'Domingo Carr',
    a11self: '-',
    a12self: '-',
    a13self: '-',
    a14self: '-',
    check1: '-',
    quick1: '-',
    a21self: '-',
    a22self: '-',
    a23self: '-',
    a24self: '-',
    check2: '-',
    quick2: '-',
    a31self: '-',
    a32self: '-',
    a33self: '-',
    a34self: '-',
    check3: '-',
    quick3: '-',
    a41self: '-',
    a42self: '-',
    a43self: '-',
    a44self: '-',
    check4: '-',
    quick4: '-',
  },
  {
    key: '5',
    student: 'Kelly Evans',
    a11self: '-',
    a12self: '-',
    a13self: '-',
    a14self: '-',
    check1: '-',
    quick1: '-',
    a21self: '-',
    a22self: '-',
    a23self: '-',
    a24self: '-',
    check2: '-',
    quick2: '-',
    a31self: '-',
    a32self: '-',
    a33self: '-',
    a34self: '-',
    check3: '-',
    quick3: '-',
    a41self: '-',
    a42self: '-',
    a43self: '-',
    a44self: '-',
    check4: '-',
    quick4: '-',
  },
  {
    key: '6',
    student: 'Cassandra Moran',
    a11self: '-',
    a12self: '-',
    a13self: '-',
    a14self: '-',
    check1: '-',
    quick1: '-',
    a21self: '-',
    a22self: '-',
    a23self: '-',
    a24self: '-',
    check2: '-',
    quick2: '-',
    a31self: '-',
    a32self: '-',
    a33self: '-',
    a34self: '-',
    check3: '-',
    quick3: '-',
    a41self: '-',
    a42self: '-',
    a43self: '-',
    a44self: '-',
    check4: '-',
    quick4: '-',
  },
  {
    key: '7',
    student: 'Nathaniel Nunez',
    a11self: '-',
    a12self: '-',
    a13self: '-',
    a14self: '-',
    check1: '-',
    quick1: '-',
    a21self: '-',
    a22self: '-',
    a23self: '-',
    a24self: '-',
    check2: '-',
    quick2: '-',
    a31self: '-',
    a32self: '-',
    a33self: '-',
    a34self: '-',
    check3: '-',
    quick3: '-',
    a41self: '-',
    a42self: '-',
    a43self: '-',
    a44self: '-',
    check4: '-',
    quick4: '-',
  },
  {
    key: '8',
    student: 'Ted Barnett',
    a11self: '-',
    a12self: '-',
    a13self: '-',
    a14self: '-',
    check1: '-',
    quick1: '-',
    a21self: '-',
    a22self: '-',
    a23self: '-',
    a24self: '-',
    check2: '-',
    quick2: '-',
    a31self: '-',
    a32self: '-',
    a33self: '-',
    a34self: '-',
    check3: '-',
    quick3: '-',
    a41self: '-',
    a42self: '-',
    a43self: '-',
    a44self: '-',
    check4: '-',
    quick4: '-',
  },
  {
    key: '9',
    student: 'Kenneth Wilson',
    a11self: '-',
    a12self: '-',
    a13self: '-',
    a14self: '-',
    check1: '-',
    quick1: '-',
    a21self: '-',
    a22self: '-',
    a23self: '-',
    a24self: '-',
    check2: '-',
    quick2: '-',
    a31self: '-',
    a32self: '-',
    a33self: '-',
    a34self: '-',
    check3: '-',
    quick3: '-',
    a41self: '-',
    a42self: '-',
    a43self: '-',
    a44self: '-',
    check4: '-',
    quick4: '-',
  },
  {
    key: '10',
    student: 'Christie  Parker',
    a11self: '-',
    a12self: '-',
    a13self: '-',
    a14self: '-',
    check1: '-',
    quick1: '-',
    a21self: '-',
    a22self: '-',
    a23self: '-',
    a24self: '-',
    check2: '-',
    quick2: '-',
    a31self: '-',
    a32self: '-',
    a33self: '-',
    a34self: '-',
    check3: '-',
    quick3: '-',
    a41self: '-',
    a42self: '-',
    a43self: '-',
    a44self: '-',
    check4: '-',
    quick4: '-',
  },
  {
    key: '11',
    student: 'Hattie  Harvey',
    a11self: '-',
    a12self: '-',
    a13self: '-',
    a14self: '-',
    check1: '-',
    quick1: '-',
    a21self: '-',
    a22self: '-',
    a23self: '-',
    a24self: '-',
    check2: '-',
    quick2: '-',
    a31self: '-',
    a32self: '-',
    a33self: '-',
    a34self: '-',
    check3: '-',
    quick3: '-',
    a41self: '-',
    a42self: '-',
    a43self: '-',
    a44self: '-',
    check4: '-',
    quick4: '-',
  },
  {
    key: '12',
    student: 'Chelsea Chavez',
    a11self: '-',
    a12self: '-',
    a13self: '-',
    a14self: '-',
    check1: '-',
    quick1: '-',
    a21self: '-',
    a22self: '-',
    a23self: '-',
    a24self: '-',
    check2: '-',
    quick2: '-',
    a31self: '-',
    a32self: '-',
    a33self: '-',
    a34self: '-',
    check3: '-',
    quick3: '-',
    a41self: '-',
    a42self: '-',
    a43self: '-',
    a44self: '-',
    check4: '-',
    quick4: '-',
  },
  {
    key: '13',
    student: 'Jessica Smith',
    a11self: '-',
    a12self: '-',
    a13self: '-',
    a14self: '-',
    check1: '-',
    quick1: '-',
    a21self: '-',
    a22self: '-',
    a23self: '-',
    a24self: '-',
    check2: '-',
    quick2: '-',
    a31self: '-',
    a32self: '-',
    a33self: '-',
    a34self: '-',
    check3: '-',
    quick3: '-',
    a41self: '-',
    a42self: '-',
    a43self: '-',
    a44self: '-',
    check4: '-',
    quick4: '-',
  },
  {
    key: '14',
    student: 'Lois  Turner',
    a11self: '-',
    a12self: '-',
    a13self: '-',
    a14self: '-',
    check1: '-',
    quick1: '-',
    a21self: '-',
    a22self: '-',
    a23self: '-',
    a24self: '-',
    check2: '-',
    quick2: '-',
    a31self: '-',
    a32self: '-',
    a33self: '-',
    a34self: '-',
    check3: '-',
    quick3: '-',
    a41self: '-',
    a42self: '-',
    a43self: '-',
    a44self: '-',
    check4: '-',
    quick4: '-',
  },
  {
    key: '15',
    student: 'Cecelia Byrd',
    a11self: '-',
    a12self: '-',
    a13self: '-',
    a14self: '-',
    check1: '-',
    quick1: '-',
    a21self: '-',
    a22self: '-',
    a23self: '-',
    a24self: '-',
    check2: '-',
    quick2: '-',
    a31self: '-',
    a32self: '-',
    a33self: '-',
    a34self: '-',
    check3: '-',
    quick3: '-',
    a41self: '-',
    a42self: '-',
    a43self: '-',
    a44self: '-',
    check4: '-',
    quick4: '-',
  },
  {
    key: '16',
    student: 'Lori  Douglas',
    a11self: '-',
    a12self: '-',
    a13self: '-',
    a14self: '-',
    check1: '-',
    quick1: '-',
    a21self: '-',
    a22self: '-',
    a23self: '-',
    a24self: '-',
    check2: '-',
    quick2: '-',
    a31self: '-',
    a32self: '-',
    a33self: '-',
    a34self: '-',
    check3: '-',
    quick3: '-',
    a41self: '-',
    a42self: '-',
    a43self: '-',
    a44self: '-',
    check4: '-',
    quick4: '-',
  },
  {
    key: '17',
    student: 'Taylor  Franklin',
    a11self: '-',
    a12self: '-',
    a13self: '-',
    a14self: '-',
    check1: '-',
    quick1: '-',
    a21self: '-',
    a22self: '-',
    a23self: '-',
    a24self: '-',
    check2: '-',
    quick2: '-',
    a31self: '-',
    a32self: '-',
    a33self: '-',
    a34self: '-',
    check3: '-',
    quick3: '-',
    a41self: '-',
    a42self: '-',
    a43self: '-',
    a44self: '-',
    check4: '-',
    quick4: '-',
  },
  {
    key: '18',
    student: 'Carroll Chambers',
    a11self: '-',
    a12self: '-',
    a13self: '-',
    a14self: '-',
    check1: '-',
    quick1: '-',
    a21self: '-',
    a22self: '-',
    a23self: '-',
    a24self: '-',
    check2: '-',
    quick2: '-',
    a31self: '-',
    a32self: '-',
    a33self: '-',
    a34self: '-',
    check3: '-',
    quick3: '-',
    a41self: '-',
    a42self: '-',
    a43self: '-',
    a44self: '-',
    check4: '-',
    quick4: '-',
  },
  {
    key: '19',
    student: 'Kim Fernandez',
    a11self: '-',
    a12self: '-',
    a13self: '-',
    a14self: '-',
    check1: '-',
    quick1: '-',
    a21self: '-',
    a22self: '-',
    a23self: '-',
    a24self: '-',
    check2: '-',
    quick2: '-',
    a31self: '-',
    a32self: '-',
    a33self: '-',
    a34self: '-',
    check3: '-',
    quick3: '-',
    a41self: '-',
    a42self: '-',
    a43self: '-',
    a44self: '-',
    check4: '-',
    quick4: '-',
  },
  {
    key: '20',
    student: 'Seth  Ramirez',
    a11self: '-',
    a12self: '-',
    a13self: '-',
    a14self: '-',
    check1: '-',
    quick1: '-',
    a21self: '-',
    a22self: '-',
    a23self: '-',
    a24self: '-',
    check2: '-',
    quick2: '-',
    a31self: '-',
    a32self: '-',
    a33self: '-',
    a34self: '-',
    check3: '-',
    quick3: '-',
    a41self: '-',
    a42self: '-',
    a43self: '-',
    a44self: '-',
    check4: '-',
    quick4: '-',
  },
];

const columns = [
  {
    title: 'Student',
    dataIndex: 'student',
    key: 'student',
    fixed: 'left',
    width: 200,
  },
  {
    title: 'Task 1.1 Self-Check',
    dataIndex: 'a11self',
    key: 'a11self',
    width: 100,
  },
  {
    title: 'Task 1.2 Self-Check',
    dataIndex: 'a12self',
    key: 'a12self',
    width: 100,
  },
  {
    title: 'Task 1.3 Self-Check',
    dataIndex: 'a13self',
    key: 'a13self',
    width: 100,
  },
  {
    title: 'Task 1.4 Self-Check',
    dataIndex: 'a14self',
    key: 'a14self',
    width: 100,
  },
  {
    title: 'Check Your Knowledge 1',
    dataIndex: 'check1',
    key: 'check1',
    width: 100,
  },
  {
    title: 'Quick Check 1',
    dataIndex: 'quick1',
    key: 'quick1',
    width: 100,
  },
  {
    title: 'Task 2.1 Self-Check',
    dataIndex: 'a21self',
    key: 'a21self',
    width: 100,
  },
  {
    title: 'Task 2.2 Self-Check',
    dataIndex: 'a22self',
    key: 'a22self',
    width: 100,
  },
  {
    title: 'Task 2.3 Self-Check',
    dataIndex: 'a23self',
    key: 'a23self',
    width: 100,
  },
  {
    title: 'Task 2.4 Self-Check',
    dataIndex: 'a24self',
    key: 'a24self',
    width: 100,
  },
  {
    title: 'Check Your Knowledge 2',
    dataIndex: 'check2',
    key: 'check2',
    width: 100,
  },
  {
    title: 'Quick Check 2',
    dataIndex: 'quick2',
    key: 'quick2',
    width: 100,
  },
  {
    title: 'Task 3.1 Self-Check',
    dataIndex: 'a31self',
    key: 'a31self',
    width: 100,
  },
  {
    title: 'Task 3.2 Self-Check',
    dataIndex: 'a32self',
    key: 'a32self',
    width: 100,
  },
  {
    title: 'Task 3.3 Self-Check',
    dataIndex: 'a33self',
    key: 'a33self',
    width: 100,
  },
  {
    title: 'Task 3.4 Self-Check',
    dataIndex: 'a34self',
    key: 'a34self',
    width: 100,
  },
  {
    title: 'Check Your Knowledge 3',
    dataIndex: 'check3',
    key: 'check3',
    width: 100,
  },
  {
    title: 'Quick Check 3',
    dataIndex: 'quick3',
    key: 'quick3',
    width: 100,
  },
  {
    title: 'Task 4.1 Self-Check',
    dataIndex: 'a41self',
    key: 'a41self',
    width: 100,
  },
  {
    title: 'Task 4.2 Self-Check',
    dataIndex: 'a42self',
    key: 'a42self',
    width: 100,
  },
  {
    title: 'Task 4.3 Self-Check',
    dataIndex: 'a43self',
    key: 'a43self',
    width: 100,
  },
  {
    title: 'Task 4.4 Self-Check',
    dataIndex: 'a44self',
    key: 'a44self',
    width: 100,
  },
  {
    title: 'Check Your Knowledge 4',
    dataIndex: 'check4',
    key: 'check4',
    width: 100,
  },
  {
    title: 'Quick Check 4',
    dataIndex: 'quick4',
    key: 'quick4',
  },  
];
const { TabPane } = Tabs;

class Dashboard extends Component {
  render() {
    return (
      <div class="drawer-content">

  <Tabs defaultActiveKey="1">
    <TabPane tab="Gradebook" key="1">
      <Table dataSource={dataSource} columns={columns} size="middle" pagination={false} scroll={{ x: 2600, y: 400 }} />;
    </TabPane>
    <TabPane tab="Analytics" key="2">
     Charts
    </TabPane>
  </Tabs>

     
     </div>
    )
  }
}

export default Dashboard; // Don’t forget to use export default!

